// <auto-generated />
using ContactAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactAPI.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20191101211043_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContactAPI.Entities.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = "d28888e9-2ba9-473a-a40f-e38cb54f9b35",
                            Address = "533 Airport blvd, suite 505, burlingame, CA 94010 ",
                            Avatar = "",
                            Birthday = "05-05-1996",
                            Company = "247pro",
                            Email = "bg@247pro.com",
                            JobTitle = "SDE",
                            LastName = "Griffin",
                            Name = "Berry",
                            NickName = "BG",
                            Notes = "Ships",
                            Phone = "1234567890"
                        },
                        new
                        {
                            Id = "c31111f2-5cqa4-156g-g20e-h62ab54f9k91",
                            Address = "1299 Bayshore hwy, rm 128, burlingame, CA 94010",
                            Avatar = "",
                            Birthday = "09-08-1995",
                            Company = "modobay",
                            Email = "BM@modobay.com",
                            JobTitle = "SDE",
                            LastName = "Mateo",
                            Name = "Ben",
                            NickName = "Benteo",
                            Notes = "Cars",
                            Phone = "9876543210"
                        },
                        new
                        {
                            Id = "a35555f2-5cqa4-156g-g20e-h62ab54f9k91",
                            Address = "1299 Bayshore hwy, rm 128, burlingame, CA 94010",
                            Avatar = "",
                            Birthday = "10-28-1994",
                            Company = "modobay",
                            Email = "PJ@modobay.com",
                            JobTitle = "Designer",
                            LastName = "Julie",
                            Name = "Penelope",
                            NickName = "PJ",
                            Notes = "Singing",
                            Phone = "9876543210"
                        },
                        new
                        {
                            Id = "f75555a2-4dd2-132d-d20d-d61dc11a2f24",
                            Address = "533 Airport blvd, suite 505, burlingame, CA 94010 ",
                            Avatar = "",
                            Birthday = "01-08-1991",
                            Company = "247pro",
                            Email = "mj@247pro.com",
                            JobTitle = "SDE",
                            LastName = "Jones",
                            Name = "Matthew",
                            NickName = "MJ",
                            Notes = "Bulls",
                            Phone = "1111111111"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
